### ISSUE TITLE
Add support for manual client registration

### ISSUE THREAD

**Issue by DrDaveD** [opensciencegrid/osg-token-renewer#13]
CILogon does not support dynamic client registration, so instead a client id & secret need to be supplied and oidc-gen invoked with the `-m` option.

**Comment by djw8605** [comment]
It does, it's just not turned on by default.

**Comment by DrDaveD** [comment]
You mean CILogon does support dynamic registration?  Well in any case I'm not convinced it's a good idea due to the risk of attacks through that method.  I think osg-token-renewer would be good for FNAL pilot frontends at least in the short term if we could use the oidc-gen manual option.

**Comment by matyasselmeci** [comment]
https://opensciencegrid.atlassian.net/browse/SOFTWARE-4983

**Comment by matyasselmeci** [comment]
How can I test this? What can I use as the client ID and secret?

**Comment by DrDaveD** [comment]
If you have an account on https://wlcg.cloud.cnaf.infn.it that would probably be the easiest way.  You can create a client id & secret under MitreId Dashboard->Self-service client registration->New client.
